# docker-compose.override.yml
# Create this file for macOS/Windows to override host networking
# Docker Compose automatically merges this with docker-compose.yml

version: "3.9"

services:
  c-vim-dev:
    # Override host networking with bridge networking
    network_mode: bridge
    
    # Add port mappings as needed
    ports:
      - "8080:8080"   # Example: if you run web servers
      - "3000:3000"   # Example: common dev ports
      - "5000:5000"   # Add more as needed
    
    # For Windows: override volumes to remove SSH agent
    volumes:
      - .:/workspace
      - dev-home:/home/dev
      # SSH agent line removed for Windows compatibility
    
    # For Windows: remove SSH environment variable
    environment: []
